# Profile 'local' - desenvolvimento na maquina conectando na stack WorldCupSpringProject.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/arenacup?currentSchema=logistics
    username: ${POSTGRES_USER:arenacup}
    password: ${POSTGRES_PASSWORD:arenacup}
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: logistics
    default-schema: logistics
  jpa:
    properties:
      hibernate:
        default_schema: logistics

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ms-logistics
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "br.com.infnet.mslogistics.kafka"
    producer:
      acks: all
      properties:
        enable.idempotence: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    br.com.infnet.mslogistics: DEBUG
    org.springframework.kafka: INFO

management:
  endpoint:
    health:
      validate-group-membership: false
