# Profile 'docker' - executando dentro do docker-compose central (WorldCupSpringProject).
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/arenacup?currentSchema=logistics
    username: ${POSTGRES_USER:arenacup}
    password: ${POSTGRES_PASSWORD:arenacup}
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: logistics
    default-schema: logistics
  jpa:
    properties:
      hibernate:
        default_schema: logistics

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ms-logistics
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "br.com.infnet.mslogistics.kafka"
    producer:
      acks: all
      properties:
        enable.idempotence: true

arenacup:
  integrations:
    core-data:
      base-url: ${CORE_DATA_BASE_URL:http://ms-core-data:8081}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    br.com.infnet.mslogistics: INFO
